### ISSUE TITLE
Please update the repository?

### ISSUE THREAD

**Issue by Neustradamus** [phpMyChat-Plus/phpmychat-plus#1]
@ciprianmp: Please update the repository?

It is not up-to-date:
- https://sourceforge.net/projects/phpmychat/files/

**Comment by ciprianmp** [comment]
Hi,

I thought github was supposed to update/sync automatically. I couldn't find a manual synchronization option. I don't intend to keep two repositories alive. I gave up, I hate github already.
Please use https://sourceforge.net/projects/phpmychat/files/

**Comment by Neustradamus** [comment]
@ciprianmp: You can have mirror yes.
- https://www.google.com/search?q=mirror+sourceforge+github

The project will have more developers here.

Thanks in advance.
